# Generated by Django 5.1.3 on 2024-11-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='moderate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='moderate',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
