# Generated by Django 5.1.3 on 2024-11-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesman',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/salesmans_photo'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/salesmans_photo'),
        ),
    ]
