# Generated by Django 5.1.3 on 2024-11-09 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_salesman_logo_image_alter_salesman_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesman',
            name='logo_image',
        ),
        migrations.AddField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesman',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesman',
            name='photo',
            field=models.ImageField(upload_to='static/salesmans_photo'),
        ),
    ]
