# Generated by Django 5.1.2 on 2024-10-29 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_recommendations_recommendation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='moderate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesman',
            name='moderate',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('is_moderate', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user')),
            ],
        ),
    ]
