# Generated by Django 5.1.2 on 2024-10-30 19:14

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_moderate_productphoto_moderate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='block_categories',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category_id',
            field=models.PositiveSmallIntegerField(choices=shop.models.category_choice, null=True),
        ),
    ]
