# Generated by Django 5.1.2 on 2024-11-06 10:13

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_category_block_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category_id',
            field=models.PositiveSmallIntegerField(blank=True, choices=shop.models.category_choice, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to='shop.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='select',
            field=models.ManyToManyField(blank=True, null=True, related_name='select', to='shop.user'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='shop.user'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='favourites_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourites', to='shop.category'),
        ),
    ]
