# Generated by Django 5.1.3 on 2024-11-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_salesman_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesman',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='shop.category'),
        ),
    ]
