# Generated by Django 5.1.3 on 2024-11-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_main_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_photo',
        ),
    ]
