# Generated by Django 5.1.3 on 2024-11-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/product_photo'),
        ),
    ]
