# Generated by Django 5.1.3 on 2024-11-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_main_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
    ]
